#  配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///1129test?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource # 使用的是HikariDataSource数据源
    hikari:
      idle-timeout: 60000 # 超时时间
      minimum-idle: 10 # 最小值
      maximum-pool-size: 20 # 最大值
# 配置mybatis
mybatis:
  type-aliases-package: com.zr.entity # 设置别名
  mapper-locations: "classpath:mapper/*.xml" # 定义mapper文件路径
#设置mybatis日志
logging:
  level:
    com.zr.dao: debug
